### ISSUE TITLE
I can't make it work on CentOS

### ISSUE THREAD

**Issue by angpa** [galindro/zabbix-enhanced-templates#1]
I have the follwing errors when I tried to install smem, could you please let me know if this enhacements templates are working for CentOS and RHEL?

Thank you in advace!

[root@server tmp]# rpm -Uvh smem-1.3-1.el6.rf.x86_64.rpm 
advertencia:smem-1.3-1.el6.rf.x86_64.rpm: CabeceraV3 DSA signature: NOKEY, key ID 6b8d79e6
error: Error de dependencias:
    rpmlib(FileDigests) <= 4.6.0-1 se necesita para smem-1.3-1.el6.rf.x86_64
    rpmlib(PayloadIsXz) <= 5.2-1 se necesita para smem-1.3-1.el6.rf.x86_64
[root@server tmp]#

**Comment by galindro** [comment]
Sorry, but I can help you with this error because I've never installed smem under CentOS / RHEL.

But, analysing the error message, it's very clear that you need to install two dependencies before install the package smem-1.3-1.el6.rf.x86_64.rpm:
rpmlib(FileDigests) <= 4.6.0-1 and rpmlib(PayloadIsXz) <= 5.2-1

So, I sugest to you to search for a solution that explains how to install those dependencies.

I'll close this thread
